// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnE2HCzzqlyKpKmPcDgHhM_XRnEoHS4Cg',
    appId: '1:747495208216:web:2984aa9f490b92f46e1a6d',
    messagingSenderId: '747495208216',
    projectId: 'jelajahnusa',
    authDomain: 'jelajahnusa.firebaseapp.com',
    storageBucket: 'jelajahnusa.firebasestorage.app',
    measurementId: 'G-V4P1JH35R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PhkJOgPXMLnezxfWeqIhp8xjojIzqyE',
    appId: '1:747495208216:android:366fbf2cb38228d06e1a6d',
    messagingSenderId: '747495208216',
    projectId: 'jelajahnusa',
    storageBucket: 'jelajahnusa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApcdlCCkXmaw8nkHT4tdxyt_HFSsGqvPs',
    appId: '1:747495208216:ios:e38f7d90b8904a8c6e1a6d',
    messagingSenderId: '747495208216',
    projectId: 'jelajahnusa',
    storageBucket: 'jelajahnusa.firebasestorage.app',
    androidClientId: '747495208216-7smcfo2v2thp14q1guo93ubdctu989nr.apps.googleusercontent.com',
    iosClientId: '747495208216-nei9mlnodpultbg6akgaop7k282fgbig.apps.googleusercontent.com',
    iosBundleId: 'com.example.jelajahNusa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApcdlCCkXmaw8nkHT4tdxyt_HFSsGqvPs',
    appId: '1:747495208216:ios:e38f7d90b8904a8c6e1a6d',
    messagingSenderId: '747495208216',
    projectId: 'jelajahnusa',
    storageBucket: 'jelajahnusa.firebasestorage.app',
    androidClientId: '747495208216-7smcfo2v2thp14q1guo93ubdctu989nr.apps.googleusercontent.com',
    iosClientId: '747495208216-nei9mlnodpultbg6akgaop7k282fgbig.apps.googleusercontent.com',
    iosBundleId: 'com.example.jelajahNusa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnE2HCzzqlyKpKmPcDgHhM_XRnEoHS4Cg',
    appId: '1:747495208216:web:ee8646975ca69f876e1a6d',
    messagingSenderId: '747495208216',
    projectId: 'jelajahnusa',
    authDomain: 'jelajahnusa.firebaseapp.com',
    storageBucket: 'jelajahnusa.firebasestorage.app',
    measurementId: 'G-JGJ7LTD8Y9',
  );

}